### ISSUE TITLE
Incorrect pading error

### ISSUE THREAD

**Issue by yurivich** [bats3c/shad0w#101]
I've just installed Shad0w and fired up the application and got a working beacon, however when I try to run any commands on the beacon I keep getting the same error : 

[2021-08-18 04:48:26,683] ERROR in app: Exception on /tasks [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/shad0w/lib/http_server.py", line 59, in web_task_beacon
    return phandle.task_beacon(request)
  File "/root/shad0w/lib/path_handler.py", line 40, in task_beacon
    beacon_id, opcode, data = tools.get_data_from_json(jdata)
  File "/root/shad0w/lib/tools.py", line 48, in get_data_from_json
    data = base64.b64decode(data).decode()
  File "/usr/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by yurivich** [comment]
Just found out that running the C2 using sudo python3 shad0w.py listen -e x.x.x.x actually works and does not give that error, but running it this way : sudo shad0w listen -e x.x.x.x does give the error

**Comment by kousha1999** [comment]
I have this problem too, and `sudo python3 shad0w.py listen -e x.x.x.x` didn't work for me!

**Comment by kousha1999** [comment]
I've found it root cause is lack of "=" in padding. I've printed the output (edited source code) and decoded by myself.
![2021-08-18_12-25](https://user-images.githubusercontent.com/36133745/129863008-0a44d8b3-80fc-41f3-9101-f8fe51a5de4b.png)
![2021-08-18_12-25_1](https://user-images.githubusercontent.com/36133745/129863084-76710d95-7d72-4b97-af78-4ac1e505784c.png)

![2021-08-18_12-24](https://user-images.githubusercontent.com/36133745/129862934-aac1d039-f593-4ce5-9951-e9f16f4c9171.png)

**Comment by bats3c** [comment]
Im aware of this issue, and will get on fixing it soon

**Comment by eqn-grp** [comment]
Did you try running directly from latest source code?

**Comment by kousha1999** [comment]
Yes.

**Comment by Adastra-thw** [comment]
I've found the same issue but not only this, almost every command that I run don't gets executed. Only works the commands that depends on other tools like the binaries in Ghospack. For example, the meterpreter command "seems to work", but the instruction is never send to the remote server. I've tried this in Windows Server 2019 and Windows 10 Home/PRO. I think this issue is related with this, for that reason I write here, but if it's another thing I can open a new issue

**Comment by eqn-grp** [comment]
i made some pull request and closed it. check recent closed pull request.

**Comment by Adastra-thw** [comment]
Yes, I've seen the pull request, the files changed are not included in master yet but in any case I've checked that it doesn't solves the issue. Applying the changes I still get "Incorrect padding" when lunch some simple commands and in other cases it (seems) don't perform any action

**Comment by cuongnguyen-git** [comment]
Hello all,
Just wondering if anyone got this working on their end? I have the same issue as everyone else.

**Comment by Adastra-thw** [comment]
> Hello all,
> Just wondering if anyone got this working on their end? I have the same issue as everyone else.

No changes in the repository, issue still present.

**Comment by ma1ware07** [comment]
Encountered this issue today, any news on the fix?

**Comment by neil-fox** [comment]
Same issue

**Comment by cr7pt0pl4gu3** [comment]
Same issue

**Comment by milldawgydawg** [comment]
Made the change to core.c as mentioned by kousha1999 and doesn't appear to solve the issue.
